name: Portfolio-builder
on: push
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: setup Node Runtime
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Dep
      run: pnpm install --no-frozen-lockfile

    - name: Validate build
      run: pnpm run build 
