name: Portfolio-builder
on: push
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: setup Node Runtime
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Dep
      run: pnpm install

    - name: Validate build
      run: ppm run build
